version: '3'

services:
  nginx:
    build:
      context: ./nginx
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    ports:
      - "${LOCAL_NGINX_PORT:-80}:80"
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code
      - ./nginx/configs/conf.d:/etc/nginx/conf.d

  pgsql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data/pgdata

