version: '3'

services:
  nginx:
    build:
      context: ./nginx
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    ports:
      - "${LOCAL_NGINX_PORT:-80}:80"
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  apache:
    build:
      context: ./apache
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    ports:
      - "80:80"
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  pgsql:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data/pgdata

  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql

  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  php5:
    build:
      context: ./php5
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  php7:
    build:
      context: ./php7
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  php71:
    build:
      context: ./php71
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data

  minio:
    image: minio/minio
    command: minio server /data
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "5050:80"
