version: '3'

services:
  nginx:
    build:
      context: ./nginx
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    ports:
      - "${LOCAL_NGINX_PORT:-80}:80"
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code
      - ./nginx/configs/conf.d:/etc/nginx/conf.d

  pgsql:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data/pgdata

  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql

  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
