version: '3'

services:
  nginx:
    build:
      context: ./nginx
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    ports:
      - "${LOCAL_NGINX_PORT:-80}:80"
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  apache:
    build:
      context: ./apache
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    ports:
      - "80:80"
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  pgsql:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data/pgdata

  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql

  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  php5:
    build:
      context: ./php5
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  php7:
    build:
      context: ./php7
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  php71:
    build:
      context: ./php71
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID:-1000}
        - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-1000}
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  elastic:
    image: elasticsearch:6.4.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:6.4.2
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-"http://elastic:9200"}
    ports:
      - "5601:5601"

  minio:
    image: minio/minio
    command: minio server /data
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "5050:80"

  jupyter:
    image: jupyter/tensorflow-notebook
    environment:
      - NB_USER=${NB_USER:-user}
      - NB_UID=${NB_UID:-1000}
      - NB_GID=${NB_GID:-1000}
      - JUPYTER_ENABLE_LAB=${JUPYTER_ENABLE_LAB:-yes}
    user: root
    ports:
      - "${LOCAL_JUPYTER_PORT:-8888}:8888"
    working_dir: "/home/${NB_USER}"
    volumes:
      - "${LOCAL_JUPYTER_ROOT}:/home/${NB_USER}"
